  # CS_161
  #
  # Module 4 makefile

  all: fallDistance.cpp smallSort.cpp hailstone.cpp
	g++ fallDistance.cpp -DDebug -o fallDistance
	g++ smallSort.cpp -DDebug -o smallSort
	g++ hailstone.cpp -DDebug -o hailstone
