# CS_162

# Lab C makefile

all : lab-d

lab-d : lab-d.cpp copy.cpp encryption.cpp toupper.cpp transformer.cpp orderedoutput.cpp lib_flip_display.cpp
	g++ lab-d.cpp copy.cpp encryption.cpp toupper.cpp transformer.cpp orderedoutput.cpp lib_flip_display.cpp -g -std=c++11 -o lab-d

clean :
	rm -f lab-d
