# CS_162

# Assignment 3 makefile

all : assignment3

assignment3 : arg_parse.cpp characterBase.cpp characterGollum.cpp characterMedusa.cpp dice.cpp \
              lib_flip_display.cpp assignment3.cpp  characterBlueMen.cpp  characterHarryPotter.cpp \
							characterReptilePeople.cpp  diceCombo.cpp

	g++ arg_parse.cpp characterBase.cpp characterGollum.cpp characterMedusa.cpp dice.cpp \
	              lib_flip_display.cpp assignment3.cpp  characterBlueMen.cpp  characterHarryPotter.cpp \
								characterReptilePeople.cpp  diceCombo.cpp -g -std=c++11 -o assignment3

clean :
	rm -f assignment3
