# CS_162

# Assignment 3 makefile

all : assignment3

assignment3 : arg_parse.cpp  assignment3.cpp  characterBase.cpp  characterMedusa.cpp  dice.cpp  diceCombo.cpp  lib_flip_display.cpp
	g++ arg_parse.cpp  assignment3.cpp  characterBase.cpp  characterMedusa.cpp  dice.cpp  diceCombo.cpp  lib_flip_display.cpp -g -std=c++11 -o assignment3

clean :
	rm -f assignment3
