# CS_162

# Assignment 3 makefile

all : lab_f

lab_f : lib_arg_parse.cpp lib_flip_display.cpp lab_f.cpp queue.cpp stack.cpp

	g++ lib_arg_parse.cpp lib_flip_display.cpp lab_f.cpp queue.cpp stack.cpp -g -std=c++11 -o lab-f

clean :
	rm -f lab-f
