# CS_162

# Lab Aa makefile

all : lab-aa

lab-aa: average.cpp summation.cpp lab-aa.cpp lib_flip_display.cpp
	g++ average.cpp summation.cpp lab-aa.cpp lib_flip_display.cpp -lncurses -o lab-aa

clean :
	rm -f lab-aa
