#!/bin/bash

#######################################################
##
## CS 344 Program 1 (Jeremy Prater)
##
## stats
##

## Exit immediately if an error occurs!
set -eE

################ Input data goes here
inputbuffer=inputdata$$
declare -A inputBuffer
x=0
y=0


################ It's a trap
## Execute cleanup function when the bash script exits
trap cleanup INT HUP QUIT TERM KILL ERR

function cleanup {
    rm -f $inputbuffer
}

## Provided rounding function
function roundNumber {
    echo $(( ( $1 + ( $2 / 2 ) ) / $2 ))
}

## Calculate the median of an array and return the median
## Handle the special case of an even number by returning the average
function calcMedian {
    read -a data <<< `echo $1 | tr " " "\n" | sort -n | tr "\n" " "`
    if [ $(( $2 % 2 )) -eq 0 ] ; then
        a=${data[$(( (( $2 )) / 2 ))]}
        b=${data[$(( (( $2  + 1)) / 2 ))]}
        echo $(( ($a + $b) / 2))
    else
        echo ${data[$(( $2 / 2 ))]}
    fi
}

## Input function that computes rows
function processRows {
    echo -e "Average\tMedian"
    for ly in `seq 0 $y`
    do
        sum=0
        median=""
        for lx in `seq 0 $x`
        do
            sum=$(( $sum + ${inputBuffer[$lx,$ly]} ))
            median="$median ${inputBuffer[$lx,$ly]}"
        done
        if [ $lx ]
        then
            lx=$(( lx + 1 ))
            printf "$(roundNumber ${sum} ${lx})"
            printf "\t"
            printf "$(calcMedian "${median}" ${lx})"
            printf "\n"
        fi
    done
}

## Input function that computes columns
function processCols {
    echo "Averages:"
    for lx in `seq 0 $x`
    do
        sum=0
        for ly in `seq 0 $y`
        do
            sum=$(( $sum + ${inputBuffer[$lx,$ly]} ))
        done
        ly=$(( ly + 1 ))
        printf "$(roundNumber ${sum} ${ly})\t"
    done
    printf "\n"


    echo "Medians:"
    for lx in `seq 0 $x`
    do
        median=""
        for ly in `seq 0 $y`
        do
            median="$median ${inputBuffer[$lx,$ly]}"
        done
        ly=$(( ly + 1 ))
        printf "$(calcMedian "${median}" ${ly})\t"
    done
    printf "\n"
}

## Get the data from the temp file (file or stdin)
function getInput {
    if [ $1 ] ; then
        cat $1 > $inputbuffer
    else
        stdinread
    fi
}

## Read the input into a buffer
function stdinread {
    cat > $inputbuffer
}

## Read input into a buffer
function readInput {
    while read -r -a buffer
    do
        x=0
        for element in "${buffer[@]}"
        do
            inputBuffer[$x,$y]=$element
            x=$(( x + 1 ))
        done
    y=$(( y + 1 ))
    done <<< `cat $inputbuffer`
    x=$(( x - 1 ))
    y=$(( y - 1 ))
}

## Print the usage and exit gracefully
function usage {
    echo "./stats {-rows|-cols} [file]"
    cleanup
    exit 1
}

#########################################
##
## Main program start
##

## Check if we have extra variables
if [ $3 ] ; then
    exit 1
fi

## ... or not enough variables
if [ ! $1 ] ; then
    exit 1
fi

## Get the input from a stream or file
getInput $2
readInput "$inputbuffer"

## Determine if we are calculating rows or columns

if [[ $1 == -r* ]] ; then
    processRows
elif [[ $1 == -c* ]] ; then
    processCols
else
    usage
fi

## Cleanup
cleanup