# CS_162

# Lab Aa makefile

all : assignment2

assignment2 : critter.cpp critterDoodleBug.cpp critterAnt.cpp assignment2.cpp
	g++ critter.cpp critterDoodleBug.cpp critterAnt.cpp assignment2.cpp lib_flip_display.cpp -g -std=c++11 -o assignment2

clean :
	rm -f assignment2
