# CS_162

# Lab Aa makefile

all : assignment2

assignment2 : critter.cpp critterDoodlebug.cpp critterAnt.cpp assignment2.cpp
	gcc critter.cpp critterDoodlebug.cpp critterAnt.cpp assignment2.cpp lib_flip_display.cpp -g -o assignment2

clean :
	rm -f assignment2
