#!/bin/bash

set -eE

pushd src

pushd keygen
rm -rf build
mkdir -p build
cd build
cmake ..
make -j 8
cp keygen ../../..
popd

pushd otp_enc_d
rm -rf build
mkdir -p build
cd build
cmake ..
make -j 8
cp otp_enc_d ../../..
popd

pushd otp_enc
rm -rf build
mkdir -p build
cd build
cmake ..
make -j 8
cp otp_enc ../../..
popd

pushd otp_dec_d
rm -rf build
mkdir -p build
cd build
cmake ..
make -j 8
cp otp_dec_d ../../..
popd

pushd otp_dec
rm -rf build
mkdir -p build
cd build
cmake ..
make -j 8
cp otp_dec ../../..
popd

popd