# CS_162

# Lab G makefile

all : lab_g

lab_g : lib_arg_parse.cpp lib_flip_display.cpp lab_g.cpp fileLoader.cpp

	g++ lib_arg_parse.cpp lib_flip_display.cpp lab_g.cpp fileLoader.cpp -g -std=c++11 -o lab-g

clean :
	rm -f lab-g
