all : cs_261_assignment_0

cs_261_assignment_0 : assignment0.cpp  lib_arg_parse.cpp  lib_flip_display.cpp

	g++ assignment0.cpp  lib_arg_parse.cpp  lib_flip_display.cpp  -g -std=c++11 -o cs_261_assignment_0

clean :
	rm -f cs_261_assignment_0
