# CS_162

# Final makefile

all : final

final : final.cpp  gameObject.cpp  gameObjects.cpp  gamePlayer.cpp  gameSpace.cpp  gameSpaceController.cpp \
        lib_arg_parse.cpp  lib_flip_display.cpp

	g++ final.cpp  gameObject.cpp  gameObjects.cpp  gamePlayer.cpp  gameSpace.cpp  gameSpaceController.cpp \
	lib_arg_parse.cpp  lib_flip_display.cpp -g -std=c++11 -o final

clean :
	rm -f final
