# CS_162

# Lab Aa makefile

all : lab-b

lab-b: dice.cpp loadeddice.cpp diceMain.cpp lib_flip_display.cpp
	g++ diceMain.cpp loadeddice.cpp dice.cpp lib_flip_display.cpp -g -o lab-b

clean :
	rm -f lab-b
	rm -f *csv
