# CS_162

# Lab Aa makefile

all : groceryList

groceryList: groceryItem.cpp groceryList.cpp lib_flip_display.cpp groceryMain.cpp
	g++ groceryItem.cpp groceryList.cpp lib_flip_display.cpp groceryMain.cpp -g -lncurses -o groceryList

clean :
	rm -f groceryList
