# CS_162

# Lab Aa makefile

all : lab-ab

lab-ab: average.cpp summation.cpp lab-ab.cpp lib_flip_display.cpp
	g++ average.cpp summation.cpp lab-ab.cpp lib_flip_display.cpp -g -o lab-ab

clean :
	rm -f lab-ab
